language: ruby
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
before_script:
  - export LANG=en_US.UTF-8 
  - export LC_ALL="en_US.UTF-8" 
  - mysql -e 'create database momentum_cms_test'
  - psql -c 'create database momentum_cms_test' -U postgres
  - rake db:migrate
script:
  - rake test
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
gemfile:
  - test/gemfiles/Gemfile.rails.4.0
  - test/gemfiles/Gemfile.rails.4.1
#  - test/gemfiles/Gemfile.rails.master
matrix:
  fast_finish: true
  allow_failures:
    - gemfile: test/gemfiles/Gemfile.rails.master
addons:
  code_climate:
    repo_token:
      secure: "HoCJzAk37VtzwVLgO3fqFhv79ndFo5sCTB/K/uBgVlfNi3wuwqouMq+BeRN17o6uLW9os3j/5u3k9dErHMbN2v1nt7CoZsbsrSpeFNvOubsYgEzquuG7c+15I1xnfUzVgxSuQglTmniHAKaqT2khrs8FpnGzvC2RtNTAr9kL0to="